language: clojure
env:
  - ES_VERSION=5.4.0 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
services:
  - postgresql
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -d
before_script:
  - sleep 30
  - psql -c 'create database clj_templates_test;' -U postgres
  - make reset
script:
  - curl 'http://localhost:9200/?pretty'
  - make clj-test-once && make cljs-test-once
jdk:
  - oraclejdk8
addons:
  postgresql: "9.6"
dist: trusty
