language: clojure
env:
  - ES_VERSION=5.4.0 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
services:
  - postgresql
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -d
before_script:
  - sleep 10
  - psql -c 'create database clj_templates_test;' -U postgres
  - make reset
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - make ci
jdk:
  - oraclejdk8
addons:
  postgresql: "9.6"
dist: trusty
sudo: required
