language: clojure
services:
  - postgresql
before_script:
  - psql -c 'create database clj_templates_test;' -U postgres
  - make reset
script: make clj-test-once && make cljs-test-once
jdk:
  - oraclejdk8
addons:
  postgresql: "9.5"
