{:group-id "yamlparser", :artifact-id "yamlparser", :description "FIXME: write description", :homepage "http://example.com/FIXME", :url "http://example.com/FIXME", :versions ["0.1.0-SNAPSHOT"]}
{:group-id "org.jmatt", :artifact-id "clojure.algo.generic", :description "clojure.algo.generic for Clojure 1.3.0. Example: (use 'clojure.algo.generic.math-functions)", :scm {:connection "scm:git:git://github.com/jmatt/algo.generic.git", :developer-connection "scm:git:ssh://git@github.com/jmatt/algo.generic.git", :tag "79d1c5cf28463ce2f5ea0b400762e73d6d59952f", :url "https://github.com/jmatt/algo.generic"}, :homepage "https://github.com/clojure/algo.generic", :url "https://github.com/clojure/algo.generic", :versions ["0.1.0-SNAPSHOT"]}
{:group-id "cljsjs", :artifact-id "responsive-nav", :description "Responsive navigation plugin without library dependencies and with fast touch screen support.", :scm {:tag "4e9adcf8cd247e66cb804d38a13f7ffb61b9046d", :url "https://github.com/cljsjs/packages"}, :homepage "http://responsive-nav.com", :url "http://responsive-nav.com", :versions ["1.0.39-0"]}
{:group-id "error.handler", :artifact-id "error.handler", :description "Error handling for clojure that goes beyond try/catch", :scm {:connection "scm:git:git://github.com/weissjeffm/error.handler.git", :developer-connection "scm:git:ssh://git@github.com/weissjeffm/error.handler.git", :tag "9f294876cac7e9e363e37140302507429013a29e", :url "https://github.com/weissjeffm/error.handler"}, :versions ["1.1.0-SNAPSHOT" "1.0.0-SNAPSHOT"]}
{:group-id "org.clojars.siscia", :artifact-id "clj-stripe", :description "Clojure binding for Stripe", :scm {:connection "scm:git:git://github.com/siscia/clj-stripe.git", :developer-connection "scm:git:ssh://git@github.com/siscia/clj-stripe.git", :tag "7d342a9beac4f1dd896d192974bdb2f13603a8bc", :url "https://github.com/siscia/clj-stripe"}, :versions ["1.0.3" "1.0.2"]}
{:group-id "session", :artifact-id "session", :description "FIXME: write this!", :scm {:connection "scm:git:git://github.com/kovasb/session.git", :developer-connection "scm:git:ssh://git@github.com/kovasb/session.git", :tag "da0aea69d6aa0905105c90be5d39645b7469eae4", :url "https://github.com/kovasb/session"}, :homepage "http://exampl.com/FIXME", :url "http://exampl.com/FIXME", :versions ["0.1.2-SNAPSHOT" "0.1.1-SNAPSHOT" "0.1.0-SNAPSHOT"]}
{:group-id "rill-event-sourcing", :artifact-id "rill.uuid", :description "An Event Sourcing Toolkit", :homepage "https://github.com/rill-event-sourcing/rill", :url "https://github.com/rill-event-sourcing/rill", :versions ["0.2.3-SNAPSHOT" "0.2.3-RC2" "0.2.3-RC1" "0.2.2" "0.2.1" "0.2.0"]}
{:group-id "com.onekingslane.danger", :artifact-id "jsonschema", :description "Library to help you derive schemas from arbirary collections of JSON", :scm {:connection "scm:git:git://github.com/okl/danger-jsonschema.git", :developer-connection "scm:git:ssh://git@github.com/okl/danger-jsonschema.git", :tag "41a5761b5182a0921df53eaaa741936e046a5d3b", :url "https://github.com/okl/danger-jsonschema"}, :versions ["1.2.2" "1.2.1" "1.1.0" "1.1.0-timestamptz" "1.0.1" "1.0.0"]}
{:group-id "im.chit", :artifact-id "hara.common.state", :description "patterns and utilities", :homepage "https://github.com/zcaudate/hara", :url "https://github.com/zcaudate/hara", :versions ["2.5.2" "2.5.1" "2.5.0" "2.4.8" "2.4.7" "2.4.6" "2.4.5" "2.4.4" "2.4.2" "2.4.0" "2.3.7" "2.3.6" "2.3.4" "2.3.3" "2.3.2" "2.3.1" "2.2.17" "2.2.16" "2.2.16-SNAPSHOT" "2.2.15" "2.2.14" "2.2.13" "2.2.12" "2.2.11" "2.2.10" "2.2.9" "2.2.7" "2.2.6" "2.2.5" "2.2.4" "2.2.3" "2.2.2" "2.2.0-SNAPSHOT" "2.1.12" "2.1.11" "2.1.10" "2.1.9" "2.1.8" "2.1.7" "2.1.6" "2.1.5" "2.1.4" "2.1.3" "2.1.2" "2.1.1"]}
{:group-id "ajom", :artifact-id "lein-template", :description "atom plugins in clojurescript", :scm {:tag "HEAD", :url "https://github.com/dvcrn/ajom"}, :homepage "https://github.com/dvcrn/ajom", :url "https://github.com/dvcrn/ajom", :versions ["0.3.2" "0.3.1" "0.3.0" "0.2.0" "0.1.1" "0.1.0"]}
{:group-id "clj-jtwig", :artifact-id "clj-jtwig", :description "Clojure wrapper for JTwig", :scm {:connection "scm:git:git://github.com/gered/clj-jtwig.git", :developer-connection "scm:git:ssh://git@github.com/gered/clj-jtwig.git", :tag "eb1c5a31a904161716c0d271e0164970d27b83c1", :url "https://github.com/gered/clj-jtwig"}, :homepage "https://github.com/gered/clj-jtwig", :url "https://github.com/gered/clj-jtwig", :versions ["0.5.1" "0.5" "0.4.1" "0.4" "0.3.2" "0.3.1" "0.2.2" "0.2.1"]}
{:group-id "xyz.a4j", :artifact-id "metrics-clojure-influxdb", :description "Clojure wrapper around InfluxDB metrics library", :scm {:connection "scm:git:git://github.com/ahjones/metrics-clojure-influxdb.git", :developer-connection "scm:git:ssh://git@github.com/ahjones/metrics-clojure-influxdb.git", :tag "557763f0fc6dea162dd5aaae34c580730b28e5e9", :url "https://github.com/ahjones/metrics-clojure-influxdb"}, :homepage "https://github.com/ahjones/metrics-clojure-influxdb", :url "https://github.com/ahjones/metrics-clojure-influxdb", :versions ["0.1.0" "0.1.0-SNAPSHOT"]}
{:group-id "clojurewerkz", :artifact-id "persephone", :description "Clojure DSL that generates [Neo4J] Cypher queries", :scm {:connection "scm:git:git://github.com/clojurewerkz/persephone.git", :developer-connection "scm:git:ssh://git@github.com/clojurewerkz/persephone.git", :tag "aafe951bd0fe22a06010937b06e765672469bf38", :url "https://github.com/clojurewerkz/persephone"}, :homepage "http://github.com/clojurewerkz/persephone", :url "http://github.com/clojurewerkz/persephone", :versions ["0.1.1"]}
{:group-id "org.clojars.jasonjckn", :artifact-id "scribe-thrift7-bindings", :description "FIXME: write description", :versions ["1.0.1" "1.0.0"]}
{:group-id "juxt.modular", :artifact-id "bootstrap", :description "A modular extension that HTML rendering of components with the Twitter Bootstrap library.", :homepage "https://github.com/juxt/modular/tree/master/modules/bootstrap", :url "https://github.com/juxt/modular/tree/master/modules/bootstrap", :versions ["0.2.0" "0.1.0"]}
{:group-id "org.clogars.mw10013", :artifact-id "remix", :description "Mix and match machinery for web and sql.", :scm {:connection "scm:git:git://github.com/mw10013/remix.git", :developer-connection "scm:git:ssh://git@github.com/mw10013/remix.git", :tag "0d0b54d84ac8815dbe5a83864e188b736da9e9b1", :url "https://github.com/mw10013/remix"}, :versions ["0.0.4"]}
{:group-id "org.clojars.ollez", :artifact-id "swingrepl", :description "A Swing Clojure REPL using BeanShell's JConsole", :scm {:connection "scm:git:git://github.com/ollez/clj-swingrepl.git", :developer-connection "scm:git:ssh://git@github.com/ollez/clj-swingrepl.git", :tag "7710eb019095507043e7356a40a3b12e35699ec5", :url "https://github.com/ollez/clj-swingrepl"}, :versions ["1.4.1-SNAPSHOT"]}
{:group-id "capstan", :artifact-id "lein-template", :description "generate a Capstan clojure project skeleton", :scm {:connection "scm:git:git://github.com/tzach/capstan-lein-plugin.git", :developer-connection "scm:git:ssh://git@github.com/tzach/capstan-lein-plugin.git", :tag "4bbeea5fcbe8bd7a1a71996f98a5d94a2d3a3ec7", :url "https://github.com/tzach/capstan-lein-plugin"}, :homepage "https://github.com/tzach/capstan-lein-plugin", :url "https://github.com/tzach/capstan-lein-plugin", :versions ["0.1.0"]}
{:group-id "nrepl-figwheel-node", :artifact-id "lein-template", :description "DEPRECATED: Leiningen template for Figwheel on nREPL and Node.js", :scm {:tag "HEAD", :url ""}, :homepage "", :url "", :versions ["0.1.6" "0.1.5" "0.1.4" "0.1.3" "0.1.2" "0.1.1-SNAPSHOT" "0.1.0"]}
{:group-id "analytics-clj", :artifact-id "analytics-clj", :description "Idiomatic Clojure wrapper for the segment.io Java client", :scm {:connection "scm:git:git://github.com/ardoq/analytics-clj.git", :developer-connection "scm:git:ssh://git@github.com/ardoq/analytics-clj.git", :tag "4bf86696d81729d543cba8ad1b0208b367421988", :url "https://github.com/ardoq/analytics-clj"}, :homepage "http://ardoq.com", :url "http://ardoq.com", :versions ["0.3.0" "0.2.2" "0.2.1" "0.2.0" "0.1.2" "0.1.1"]}
{:group-id "ryane", :artifact-id "hiroba", :description "A minimalistic Clojure library for the Foursquare REST API - forked from https://github.com/mochify/hiroba", :scm {:connection "scm:git:git://github.com/ryane/hiroba.git", :developer-connection "scm:git:ssh://git@github.com/ryane/hiroba.git", :tag "33012ab85c5095c03e735d851aed0fb78e142b06", :url "https://github.com/ryane/hiroba"}, :homepage "https://github.com/ryane/hiroba", :url "https://github.com/ryane/hiroba", :versions ["0.1.0-alpha2-SNAPSHOT"]}
{:group-id "org.clojars.mpenet", :artifact-id "clj-redis", :scm {:connection "scm:git:git://github.com/mpenet/clj-redis.git", :developer-connection "scm:git:ssh://git@github.com/mpenet/clj-redis.git", :tag "57eb3b57db954c66379bd2be1f3ee8b9269e933b", :url "https://github.com/mpenet/clj-redis"}, :versions ["0.0.8" "0.0.8-SNAPSHOT"]}
{:group-id "containium.systems", :artifact-id "elasticsearch", :description "ElasticSearch Containium System", :scm {:connection "scm:git:git://github.com//.git", :developer-connection "scm:git:ssh://git@github.com//.git", :tag "e3e50e3002847df9c169a9475a635469561df981", :url "https://github.com//"}, :homepage "http://containium.org", :url "http://containium.org", :versions ["0.1.1" "0.1.0" "0.1.0-SNAPSHOT"]}
{:group-id "clj-bucket", :artifact-id "clj-bucket", :description "A low-level implementation of the token bucket algorithm", :scm {:tag "HEAD", :url "https://github.com/sgerguri/clj-bucket"}, :homepage "https://github.com/sgerguri/clj-bucket", :url "https://github.com/sgerguri/clj-bucket", :versions ["0.2.0" "0.1.5" "0.1.4" "0.1.3" "0.1.2"]}
{:group-id "pleasetrythisathome", :artifact-id "tao", :description "Two way data binding for browser history", :scm {:connection "scm:git:git://github.com/pleasetrythisathome/tao.git", :developer-connection "scm:git:ssh://git@github.com/pleasetrythisathome/tao.git", :tag "cedb3f7b5d51f6578294f1cf11b26a773d906ae5", :url "https://github.com/pleasetrythisathome/tao"}, :homepage "http://github.com/pleasetrythisathome/tao", :url "http://github.com/pleasetrythisathome/tao", :versions ["0.1.5" "0.1.4" "0.1.3" "0.1.2" "0.1.1" "0.1.1-SNAPSHOT" "0.1.0-SNAPSHOT"]}
{:group-id "net.thegeez", :artifact-id "google-closure-library", :description "The Google Closure Library is a collection of JavaScript code\n    designed for use with the Google Closure JavaScript Compiler.\n \n    Non-official distribution for usage with the ClojureScript.", :scm {:connection "scm:svn:http://closure-library.googlecode.com/svn/trunk", :developer-connection "scm:svn:http://closure-library.googlecode.com/svn/trunk", :tag "HEAD", :url "http://code.google.com/p/closure-library/source/browse/#svn/trunk"}, :homepage "http://code.google.com/p/closure-library/", :url "http://code.google.com/p/closure-library/", :versions ["0.0-1698"]}
{:group-id "aviary", :artifact-id "figwheel", :description "ClojureScript Autobuilder/Server which pushes changed files to the browser.", :scm {:tag "HEAD", :url "https://github.com/bhauman/lein-figwheel"}, :homepage "https://github.com/bhauman/lein-figwheel", :url "https://github.com/bhauman/lein-figwheel", :versions ["0.2.5"]}
{:group-id "shale", :artifact-id "shale", :description "A Clojure-backed Selenium hub replacement", :scm {:tag "HEAD", :url "http://github.com/cardforcoin/shale"}, :homepage "https://github.com/cardforcoin/shale", :url "https://github.com/cardforcoin/shale", :versions ["0.3.3" "0.3.3-SNAPSHOT" "0.3.1" "0.3.0" "0.2.2" "0.2.1" "0.2.0" "0.1.1" "0.1.0"]}
{:group-id "org.pingles", :artifact-id "rotary", :description "Amazon DynamoDB API", :scm {:connection "scm:git:git://github.com/pingles/rotary.git", :developer-connection "scm:git:ssh://git@github.com/pingles/rotary.git", :tag "8ca0525f2f559c4ff1a1050a272bff32bb17cfb9", :url "https://github.com/pingles/rotary"}, :versions ["0.4.1-SNAPSHOT"]}
{:group-id "org.clojars.turbopape", :artifact-id "milestones", :description "Milestones : the Automagic Project Planner", :scm {:tag "HEAD", :url "https://github.com/turbopape/milestones.git"}, :homepage "http://turbopape.github.io/milestones", :url "http://turbopape.github.io/milestones", :versions ["1.0.1" "1.0.0" "0.3.0" "0.2.0"]}
{:group-id "keorn", :artifact-id "loom-gorilla", :description "A Gorilla REPL renderer for loom graphs.", :scm {:connection "scm:git:git://github.com/JonyEpsilon/loom-gorilla.git", :developer-connection "scm:git:ssh://git@github.com/JonyEpsilon/loom-gorilla.git", :tag "dbdd77076274c4c5672dd1891b68d7952eccc530", :url "https://github.com/JonyEpsilon/loom-gorilla"}, :homepage "https://github.com/JonyEpsilon/loom-gorilla", :url "https://github.com/JonyEpsilon/loom-gorilla", :versions ["0.1.1-SNAPSHOT"]}
{:group-id "suvash", :artifact-id "irclj", :description "A simple IRC library/bot framework.", :scm {:connection "scm:git:git://github.com/suvash/irclj.git", :developer-connection "scm:git:ssh://git@github.com/suvash/irclj.git", :tag "4c3ef716d27e00b6e057792ff9ffd12f026f8114", :url "https://github.com/suvash/irclj"}, :homepage "https://github.com/flatland/irclj", :url "https://github.com/flatland/irclj", :versions ["0.5.0-alpha4" "0.5.0-alpha3"]}
{:group-id "selfsame", :artifact-id "pdf", :description "Predicate dispatch for Clojure(Script).", :scm {:connection "scm:git:git://github.com/selfsame/pdf.git", :developer-connection "scm:git:ssh://git@github.com/selfsame/pdf.git", :tag "01e0d677a251ecb6b6c55e3afd015fd5d5b2305f", :url "https://github.com/selfsame/pdf"}, :homepage "http://github.com/selfsame/pdf", :url "http://github.com/selfsame/pdf", :versions ["0.0.9.5-SNAPSHOT" "0.0.9-SNAPSHOT"]}
{:group-id "argo", :artifact-id "argo", :description "JSON API implementation for Clojure", :scm {:tag "HEAD", :url "https://github.com/stephenmuss/argo"}, :homepage "http://github.com/stephenmuss/argo", :url "http://github.com/stephenmuss/argo", :versions ["0.1.2" "0.1.1" "0.1.0" "0.1.0-SNAPSHOT"]}
{:group-id "com.report.engine", :artifact-id "clients", :versions ["0.0.3-SNAPSHOT" "0.0.2-SNAPSHOT"]}
{:group-id "fw1", :artifact-id "boot-template", :description "FW/1 template for Boot new", :scm {:tag "c8449a35cde2b162e5c8d47fb4369b2db8482dd5", :url "https://github.com/framework-one/fw1-template/"}, :homepage "https://github.com/framework-one/fw1-template/", :url "https://github.com/framework-one/fw1-template/", :versions ["0.8.0" "0.5.2" "0.5.1" "0.5.0"]}
{:group-id "chrisbetz", :artifact-id "sparkling", :description "A Clojure Library for Apache Spark", :scm {:connection "scm:git:git://github.com//.git", :developer-connection "scm:git:ssh://git@github.com//.git", :tag "2779039522606d2df323e624064236c8c0ebb569", :url "https://github.com//"}, :homepage "https://github.com/chrisbetz/sparkling", :url "https://github.com/chrisbetz/sparkling", :versions ["1.0.0-SNAPSHOT"]}
{:group-id "org.clojars.guv", :artifact-id "jmxremote_optional", :versions ["1.0.1_04"]}
{:group-id "parser", :artifact-id "parser", :scm {:connection "scm:git:git://github.com/dsp/geocommit-parser.git", :developer-connection "scm:git:ssh://git@github.com/dsp/geocommit-parser.git", :tag "ac9c60d84b65697ccdb7c3852b84e315be2d7324", :url "https://github.com/dsp/geocommit-parser"}, :versions ["1.0.0"]}
{:group-id "ragtime-c.j.j-0.3.3", :artifact-id "ragtime-c.j.j-0.3.3", :description "A database-independent migration library", :scm {:connection "scm:git:git://github.com/ddellacosta/ragtime.git", :developer-connection "scm:git:ssh://git@github.com/ddellacosta/ragtime.git", :tag "5332bfa2ca98b6e6c78ecae5e9f129c7a527f375", :url "https://github.com/ddellacosta/ragtime"}, :versions ["0.3.4-2" "0.3.4-1" "0.3.4"]}
{:group-id "marshallbrekka", :artifact-id "clj-aws-s3", :description "Clojure Amazon S3 library.", :scm {:connection "scm:git:git://github.com/marshallbrekka/clj-aws-s3.git", :developer-connection "scm:git:ssh://git@github.com/marshallbrekka/clj-aws-s3.git", :tag "528beb3e9c7b2b6a924d92ecef3fd456292cb54a", :url "https://github.com/marshallbrekka/clj-aws-s3"}, :versions ["0.3.5" "0.3.5a"]}
{:group-id "hoptoad", :artifact-id "hoptoad-java-notifier", :versions ["1.9"]}
{:group-id "cljsjs", :artifact-id "blend4web", :description "Blend4Web -- Javascript WebGL Framework by Triump LLC", :scm {:tag "ea893d7be7b7ca32328e8c484d954cb8e2681b1b", :url "https://github.com/cljsjs/packages"}, :homepage "http://www.blend4web.org/", :url "http://www.blend4web.org/", :versions ["16.11-1"]}
{:group-id "provisdom-clj", :artifact-id "boot-template", :description "The provisdom boot-new template", :scm {:tag "c7cf590021ebff82e63b4f721ff1d9ebd29b5be5", :url "https://github.com/Provisdom/clj-boot-template"}, :homepage "https://github.com/Provisdom/clj-boot-template", :url "https://github.com/Provisdom/clj-boot-template", :versions ["0.2.4" "0.2.3" "0.2.2" "0.2.1" "0.2.0" "0.2.0-SNAPSHOT" "0.1.1" "0.1.1-SNAPSHOT" "0.1.0"]}
{:group-id "org.ozias.cljlibs", :artifact-id "semver", :description "Semantic version-ing library for Clojure", :scm {:tag "HEAD", :url "https://github.com/CraZySacX/semver"}, :homepage "https://github.com/CraZySacX/semver", :url "https://github.com/CraZySacX/semver", :versions ["0.1.5-SNAPSHOT" "0.1.4" "0.1.4-SNAPSHOT" "0.1.3" "0.1.3-SNAPSHOT" "0.1.2" "0.1.2-SNAPSHOT" "0.1.1" "0.1.1-SNAPSHOT" "0.1.1-alpha.0" "0.1.0-SNAPSHOT" "0.1.0-alpha.1" "0.1.0-alpha.0"]}
{:group-id "quile", :artifact-id "dependency-cljs", :description "A data structure for representing dependency graphs", :scm {:connection "scm:git:git://github.com/quile/dependency.git", :developer-connection "scm:git:ssh://git@github.com/quile/dependency.git", :tag "010b241c7667d6a685e0b55551edcab1e3caa085", :url "https://github.com/quile/dependency"}, :homepage "https://github.com/quile/dependency-cljs", :url "https://github.com/quile/dependency-cljs", :versions ["0.1.4"]}
{:group-id "tcp-server", :artifact-id "tcp-server", :description "Threaded TCP server library", :scm {:connection "scm:git:git://github.com/weavejester/tcp-server.git", :developer-connection "scm:git:ssh://git@github.com/weavejester/tcp-server.git", :tag "553607c1af3337ca5ac85f90d30683a021db100d", :url "https://github.com/weavejester/tcp-server"}, :versions ["0.1.0"]}
{:group-id "org.clojars.dlepage", :artifact-id "clj-cassandra", :description "Clojure client for Apache Cassandra", :versions ["0.1.3"]}
{:group-id "org.clojars.danielbraun", :artifact-id "expresso", :description "a general Algebraic Expression manipulation library in clojure", :scm {:connection "scm:git:git://github.com/clojure-numerics/expresso.git", :developer-connection "scm:git:ssh://git@github.com/clojure-numerics/expresso.git", :tag "71707402fcdde3bc2c17cd4c89e1220c978a1d5e", :url "https://github.com/clojure-numerics/expresso"}, :homepage "https://github.com/clojure-numerics/expresso", :url "https://github.com/clojure-numerics/expresso", :versions ["0.2.2-SNAPSHOT"]}